#!/usr/bin/env python3
import sys
import socket
import time
from threading import Thread

server_name = sys.argv[1]
config_file = sys.argv[2]

server_ip = ""
server_port = 0
MAX_BUFFER_SIZE = 500

txn_count = 0
accounts = {}
wts = {}
rts = {}
txn_list = {}
depend_list = {}
abort_list = {}

with open(config_file) as f:
    lines = f.readlines()

for line in lines:
    info = line.split()
    if info[0] == server_name:
        server_ip = info[1]
        server_port = int(info[2])

def accept_incoming_connections(ip,port):
    soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # soc.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
    soc.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

    try:
        soc.bind((ip, port))
    except:
        print('Bind failed. Error : ' + str(sys.exc_info()))
        sys.exit()

    soc.listen(100)
    while(True):
        connection, address = soc.accept()
        ip, port = str(address[0]), str(address[1])
        print('Connected with ' + ip + ':' + port)
        #setup_msg = connection.recv(MAX_BUFFER_SIZE, socket.MSG_WAITALL).decode('utf8').strip()
        #setup = setup_msg.split()
        #ip, port = setup[0], int(setup[1])

        try:
            #print("Starting service thread")
            Thread(target=node_receive,args=(connection, ip, port)).start()
        except:
            print('Thread did not start.')
            traceback.print_exc()

def node_receive(connection,ip,port):
    #client_soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    #client_soc.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    #client_soc.connect((ip,int(port)))

    global txn_count
    txn_num = 0
    while True:
        client_msg = connection.recv(MAX_BUFFER_SIZE).decode('utf8').strip()
        print(client_msg)
        msg = client_msg.split()
        if(len(msg)) == 0:
            break
        msg_typ = msg[0]
        acc_found = 0
        bal = 0
        if msg_typ == "DEPOSIT" or msg_typ == "WITHDRAW" or msg_typ == "BALANCE":
            accn = msg[1].split(".")
            acc = accn[1]
            txn = txn_list[txn_num]
            match_txn = 0
            #if acc in txn:
            #    acc_found = 1
            #else:
            #    if acc in accounts:
            #        acc_found = 2

            #if acc in lts:
            #    if lts[acc] > txn_num:
            #        abort_list[txn_num] = 1
            for tn in txn_list:
                if acc in txn_list[tn] and tn > match_txn:
                    acc_found = 1
                    match_txn = tn
                    bal = txn_list[tn][acc]
            if acc_found == 1:
                if match_txn != txn_num:
                    if match_txn not in depend_list:
                        depend_list[match_txn] = []
                    depend_list[match_txn].append(txn_num)
            else:
                if acc in accounts:
                    acc_found = 2
                    bal = accounts[acc]

        if msg_typ == "BEGIN":
            txn_count += 1
            txn_num = txn_count
            print(txn_num)
            new_txn = {}
            txn_list[txn_count] = new_txn
        elif msg_typ == "DEPOSIT":
            if acc in rts:
                if txn_num < rts[acc]:
                    abort_list[txn_num] = 1
                else:
                    rts[acc] = txn_num
            else:
                rts[acc] = txn_num
            if acc in wts:
                if txn_num < wts[acc]:
                    abort_list[txn_num] = 1
                else:
                    wts[acc] = txn_num
            else:
                wts[acc] = txn_num
            txn = txn_list[txn_num]
            if acc_found == 0:
                txn[acc] = int(msg[2])
            else:
                txn[acc] = bal + int(msg[2])
            txn_list[txn_num] = txn
            m = "OK"
            connection.sendall(m.encode('utf8'))
        elif msg_typ == "WITHDRAW":
            if acc in rts:
                if txn_num < rts[acc]:
                    abort_list[txn_num] = 1
                else:
                    rts[acc] = txn_num
            else:
                rts[acc] = txn_num
            if acc in wts:
                if txn_num < wts[acc]:
                    abort_list[txn_num] = 1
                else:
                    wts[acc] = txn_num
            else:
                wts[acc] = txn_num
            txn = txn_list[txn_num]
            if acc_found == 0:
                m = "NOT FOUND, ABORTED"
                connection.sendall(m.encode('utf8'))
                continue
            else:
                txn[acc] = bal - int(msg[2])
            txn_list[txn_num] = txn
            m = "OK"
            connection.sendall(m.encode('utf8'))
        elif msg_typ == "BALANCE":
            if acc in wts:
                if txn_num < wts[acc]:
                    abort_list[txn_num] = 1
            if acc in rts:
                if txn_num > rts[acc]:
                    rts[acc] = txn_num
            txn = txn_list[txn_num]
            if acc_found == 0:
                m = "NOT FOUND, ABORTED"
                connection.sendall(m.encode('utf8'))
                continue
            m = msg[1] + " = " + str(bal)
            connection.sendall(m.encode('utf8'))
        elif msg_typ == "CAN_COMMIT":
            while True:
                time.sleep(1)
                wait_ts = 0
                for t in txn_list:
                    if t < txn_num:
                        wait_ts = 1
                if wait_ts == 0:
                    break
            txn = txn_list[txn_num]
            abort = 0
            if txn_num in abort_list:
                abort = 1
                if txn_num in depend_list:
                    deps = depend_list[txn_num]
                    for dep in deps:
                        abort_list[dep] = 1
            for a in txn:
                if txn[a] < 0:
                    abort = 1
            if abort:
                m = "ABORTED"
            else:
                m = "YES_COMMIT"
            connection.sendall(m.encode('utf8'))
        elif msg_typ == "DO_COMMIT":
            txn = txn_list[txn_num]
            for a in txn:
                accounts[a] = txn[a]
            txn_list.pop(txn_num,f)
        elif msg_typ == "ABORT":
            abort_list[txn_num] = 1
            if txn_num in depend_list:
                deps = depend_list[txn_num]
                for dep in deps:
                    abort_list[dep] = 1
            txn_list.pop(txn_num,f)


Thread(target=accept_incoming_connections,args=(server_ip,server_port)).start()
time.sleep(10)
